apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |
      - op: add
        path: /metadata/namespace
        value: y3pm8
    target:
      name: podinfo
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml

